# Generated by Django 3.2.3 on 2022-05-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmemoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('mcs_no', models.FloatField(blank=True, null=True)),
                ('mcs_co', models.FloatField(blank=True, null=True)),
                ('mcs_co2', models.FloatField(blank=True, null=True)),
                ('mcs_n2o', models.FloatField(blank=True, null=True)),
                ('mcs_nh3', models.FloatField(blank=True, null=True)),
                ('mcs_hcl', models.FloatField(blank=True, null=True)),
                ('mcs_so2_med', models.FloatField(blank=True, null=True)),
                ('mcs_so2_hi', models.FloatField(blank=True, null=True)),
                ('mcs_h2o', models.FloatField(blank=True, null=True)),
                ('mcs_o2', models.FloatField(blank=True, null=True)),
                ('t_bk', models.FloatField(blank=True, null=True)),
                ('coal_cond', models.FloatField(blank=True, null=True)),
                ('d_p_bg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('t1_br_actual', models.FloatField(blank=True, null=True)),
                ('t3_br_actual', models.FloatField(blank=True, null=True)),
                ('t4_br_actual', models.FloatField(blank=True, null=True)),
                ('t1_bk_actual', models.FloatField(blank=True, null=True)),
                ('t1_bk_target', models.FloatField(blank=True, null=True)),
                ('t2_bk_actual', models.FloatField(blank=True, null=True)),
                ('t2_bk_target', models.FloatField(blank=True, null=True)),
                ('t3_bk_actual', models.FloatField(blank=True, null=True)),
                ('t3_bk_target', models.FloatField(blank=True, null=True)),
                ('t4_bk_actual', models.FloatField(blank=True, null=True)),
                ('t4_bk_target', models.FloatField(blank=True, null=True)),
                ('t5_bk_actual', models.FloatField(blank=True, null=True)),
                ('t5_bk_target', models.FloatField(blank=True, null=True)),
                ('t6_bk_actual', models.FloatField(blank=True, null=True)),
                ('t2_rz_actual', models.FloatField(blank=True, null=True)),
                ('t2_rz_target', models.FloatField(blank=True, null=True)),
                ('t3_rz_actual', models.FloatField(blank=True, null=True)),
                ('t3_rz_target', models.FloatField(blank=True, null=True)),
                ('t1_rg_actual', models.FloatField(blank=True, null=True)),
                ('t1_rg_target', models.FloatField(blank=True, null=True)),
                ('t2_rg_actual', models.FloatField(blank=True, null=True)),
                ('t1_ms_actual', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('t2_ms_actual', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('t3_ms_actual', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('t4_ms_actual', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('p1_br_actual', models.FloatField(blank=True, null=True)),
                ('p1_br_target', models.FloatField(blank=True, null=True)),
                ('p1_r_actual', models.FloatField(blank=True, null=True)),
                ('p1_rg_actual', models.FloatField(blank=True, null=True)),
                ('p1_rlkl_actual', models.FloatField(blank=True, null=True)),
                ('p1_rz_actual', models.FloatField(blank=True, null=True)),
                ('p2_rz_actual', models.FloatField(blank=True, null=True)),
                ('dp1_rg_actual', models.FloatField(blank=True, null=True)),
                ('dp1_rz_actual', models.FloatField(blank=True, null=True)),
                ('dp2_rz_actual', models.FloatField(blank=True, null=True)),
                ('coal_m_actual', models.FloatField(blank=True, null=True)),
                ('m1_rz_actual', models.FloatField(blank=True, null=True)),
                ('m1_rz_target', models.FloatField(blank=True, null=True)),
                ('m2_rz_actual', models.FloatField(blank=True, null=True)),
                ('m2_rz_target', models.FloatField(blank=True, null=True)),
                ('m1_rl_actual', models.FloatField(blank=True, null=True)),
                ('m1_rl_target', models.FloatField(blank=True, null=True)),
                ('m2_rl_actual', models.FloatField(blank=True, null=True)),
                ('m2_rl_target', models.FloatField(blank=True, null=True)),
                ('mfc1_o2_actual', models.FloatField(blank=True, null=True)),
                ('mfc1_o2_target', models.FloatField(blank=True, null=True)),
                ('mfc2_o2_actual', models.FloatField(blank=True, null=True)),
                ('mfc2_o2_target', models.FloatField(blank=True, null=True)),
                ('coal_density', models.FloatField(blank=True, null=True)),
                ('venturi_density', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
